--- #YAML:1.0
name:               Plack-Middleware-Session-FixationDefender
version:            0.04b
abstract:           Plack::Middleware::Session + fixation block
author:
    - Shinichiro Aska <s.aska.org@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Plack::Middleware::Session:  0
    Test::More:           0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
